language: rust
matrix:
  fast_finish: true

jdk:
  - oraclejdk9

sudo: false

branches:
  only:
    - master

before_install:
  - wget -O zookeeper.tar.gz http://archive.apache.org/dist/zookeeper/zookeeper-${ZOOKEEPER_VERSION}/zookeeper-${ZOOKEEPER_VERSION}.tar.gz
  - mkdir zookeeper
  - tar -zxvf zookeeper.tar.gz -C zookeeper --strip-components 1

before_script:
  - ./travis/before_script.sh

env:
  matrix:
    - ZOOKEEPER_VERSION=3.4.13